---
- name: install kubeflow v1.6
  hosts: master
  become: yes
  gather_facts: yes

  tasks:
    - name: check the servers' os version
      when: >
        (ansible_distribution != 'CentOS')

        or

        (ansible_distribution_version != '7.9')
      meta: end_play

    - name: setup master node
      when:
        - admin is not defined
        - master_ip not defined
      meta: end_play

    - name: download kubeflow git repository
      become_user: "{{ admin }}"
      git:
        repo: 'https://github.com/kubeflow/manifests.git'
        dest: $HOME/manifests
        version: v1.6-branch
        force: yes
      register: output

    - name: change MASTER_IP to master_ip in certificate.yaml
      become_user: "{{ admin }}"
      replace:
        regexp: 'MASTER_IP'
        replace: "{{ master_ip }}"
        path: $HOME/kubeflow_centos_ansible/files/certificate.yaml
      register: output

    - name: insert https redirection code in kf-istio-resources.yaml
      become_user: "{{ admin }}"
      shell: |
        cat << EOF >> $HOME/manifests/common/istio-1-14/kubeflow-istio-resources/base/kf-istio-resources.yaml
            tls:
              httpsRedirect: true
          - hosts:
            - '*'
            port:
              name: https
              number: 443
              protocol: HTTPS
            tls:
              mode: SIMPLE
              privateKey: /etc/istio/ingressgateway-certs/tls.key
              serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
        EOF
      register: output

    - name: change true to false in params.env file
      become_user: "{{ admin }}"
      replace:
        regexp: 'true'
        replace: 'false'
        path: $HOME/manifests/apps/jupyter/jupyter-web-app/upstream/base/params.env
      register: output

    - name: download kustomize
      get_url:
        url: https://github.com/kubernetes-sigs/kustomize/releases/download/v3.2.0/kustomize_3.2.0_linux_amd64
        dest: /usr/bin/kustomize
        mode:  0777
      register: output
