---
- name: install gpu operator
  hosts: master
  become: yes
  gather_facts: yes

  tasks:
    - name: check the servers' os version
      when: >
        (ansible_distribution != 'CentOS')

        or

        (ansible_distribution_version != '7.9')
      meta: end_play

    - name: setup master node
      when:
        - admin is not defined
      meta: end_play    

    - name: add nvidia helm repository
      become_user: "{{ admin }}"
      kubernetes.core.helm_repository:
        name: nvidia
        repo_url: https://helm.ngc.nvidia.com/nvidia
      register: output

    - name: update helm repo
      become_user: "{{ admin }}"
      shell: helm repo update
      register: output

    - name: install gpu operator
      become_user: "{{ admin }}"
      shell: |
        helm install --wait --generate-name \
        -n gpu-operator --create-namespace \
        nvidia/gpu-operator
        --set toolkit.version=1.7.1-centos7
      register: output
      
# uninstall gpu operator : helm delete -n gpu-operator $(helm list -n gpu-operator | grep gpu-operator | awk '{print $1}')
